// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: protos/supply.proto

package supplies

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SupplierClient is the client API for Supplier service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SupplierClient interface {
	GetStock(ctx context.Context, in *Product, opts ...grpc.CallOption) (*Product, error)
}

type supplierClient struct {
	cc grpc.ClientConnInterface
}

func NewSupplierClient(cc grpc.ClientConnInterface) SupplierClient {
	return &supplierClient{cc}
}

func (c *supplierClient) GetStock(ctx context.Context, in *Product, opts ...grpc.CallOption) (*Product, error) {
	out := new(Product)
	err := c.cc.Invoke(ctx, "/Supplier/GetStock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SupplierServer is the server API for Supplier service.
// All implementations must embed UnimplementedSupplierServer
// for forward compatibility
type SupplierServer interface {
	GetStock(context.Context, *Product) (*Product, error)
	mustEmbedUnimplementedSupplierServer()
}

// UnimplementedSupplierServer must be embedded to have forward compatible implementations.
type UnimplementedSupplierServer struct {
}

func (UnimplementedSupplierServer) GetStock(context.Context, *Product) (*Product, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStock not implemented")
}
func (UnimplementedSupplierServer) mustEmbedUnimplementedSupplierServer() {}

// UnsafeSupplierServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SupplierServer will
// result in compilation errors.
type UnsafeSupplierServer interface {
	mustEmbedUnimplementedSupplierServer()
}

func RegisterSupplierServer(s grpc.ServiceRegistrar, srv SupplierServer) {
	s.RegisterService(&Supplier_ServiceDesc, srv)
}

func _Supplier_GetStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Product)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupplierServer).GetStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Supplier/GetStock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupplierServer).GetStock(ctx, req.(*Product))
	}
	return interceptor(ctx, in, info, handler)
}

// Supplier_ServiceDesc is the grpc.ServiceDesc for Supplier service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Supplier_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Supplier",
	HandlerType: (*SupplierServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStock",
			Handler:    _Supplier_GetStock_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/supply.proto",
}
